// ---------------------------------------------------------------------------
// 2026 FIFA World Cup — snapshot data as of July 4, 2026 (Round of 16 kickoff)
// Sourced from live news coverage at build time. The tournament moves fast —
// edit RESULTS / FIXTURES below to keep it current as later rounds are played.
// ---------------------------------------------------------------------------

// Playstyle categories used to classify every team
const STYLES = {
  POSSESSION: { label: "Possession & Passing", color: "#2e7dd7" },
  PRESS:      { label: "Aggressive Press",      color: "#d1453b" },
  COUNTER:    { label: "Counter-Attack",        color: "#e08e0b" },
  PARK_BUS:   { label: "Park the Bus",          color: "#5a5f66" },
  DIRECT:     { label: "Direct & Physical",     color: "#8a4fd1" },
  TOTAL:      { label: "Total Football",        color: "#1fa774" },
  BALANCED:   { label: "Balanced / Pragmatic",  color: "#c9a227" },
};

// Every team that reached the Round of 32.
//   code     — ISO code for flag images (flagcdn.com)
//   strength — long-term squad quality (0-100)
//   form     — how good they've actually looked IN THIS TOURNAMENT (0-100),
//              with formNote citing the real results behind the number.
//              The prediction model blends strength (65%) with form (35%).
const TEAMS = {
  "Argentina":              { code: "ar", flag: "🇦🇷", strength: 92, form: 93, style: "BALANCED",
    formNote: "Messi leads the golden boot race with 6 goals; cruised through the group stage as defending champions.",
    blurb: "Controls games through midfield discipline but happily drops deep and counters when ahead." },
  "France":                 { code: "fr", flag: "🇫🇷", strength: 91, form: 93, style: "COUNTER",
    formNote: "Mbappé shares the golden boot lead (6 goals) and France dismantled Sweden 3-0 in the round of 32.",
    blurb: "Doesn't need to dominate the ball — wins it back and breaks at explosive pace through Mbappé and co. Lower possession than Spain, but ruthless in transition." },
  "Spain":                  { code: "es", flag: "🇪🇸", strength: 90, form: 92, style: "POSSESSION",
    formNote: "Swept Austria aside 3-0 — arguably the most complete performance of the round of 32.",
    blurb: "Modern tiki-taka heir: relentless short passing to suffocate opponents out of the game." },
  "Brazil":                 { code: "br", flag: "🇧🇷", strength: 88, form: 84, style: "POSSESSION",
    formNote: "Only 2-1 past Japan in the round of 32 — a narrower, more laboured win than a title favorite would like.",
    blurb: "Technical, flair-driven possession built around quick combinations in tight spaces." },
  "England":                { code: "gb-eng", flag: "🏴", strength: 87, form: 83, style: "BALANCED",
    formNote: "Edged DR Congo 2-1 — got the job done, but far from convincing against the weakest side left.",
    blurb: "Patient build-up with license to go direct through pacey wide forwards." },
  "Portugal":               { code: "pt", flag: "🇵🇹", strength: 86, form: 88, style: "COUNTER",
    formNote: "Beat Croatia 2-1 — the standout head-to-head result of the round of 32.",
    blurb: "Compact defensively, explosive on the break with direct running in behind." },
  "Netherlands":            { code: "nl", flag: "🇳🇱", strength: 85, form: 76, style: "TOTAL",
    formNote: "Out — held 1-1 by Morocco and beaten 3-2 on penalties despite a goal-heavy group stage.",
    blurb: "Fluid positional rotations, high defensive line, everyone attacks and defends." },
  "Germany":                { code: "de", flag: "🇩🇪", strength: 83, form: 74, style: "PRESS",
    formNote: "Out — drew 1-1 with Paraguay and lost the shootout 4-3 in the round of 32.",
    blurb: "Coordinated high press aiming to win the ball in the opponent's third." },
  "Belgium":                { code: "be", flag: "🇧🇪", strength: 82, form: 79, style: "COUNTER",
    formNote: "Survived a 3-2 extra-time thriller against Senegal — dangerous going forward, leaky at the back.",
    blurb: "Sits in a mid-block and springs quick vertical counters through creative midfielders." },
  "Croatia":                { code: "hr", flag: "🇭🇷", strength: 82, form: 78, style: "POSSESSION",
    formNote: "Out — competitive to the end but beaten 2-1 by Portugal.",
    blurb: "Wins the midfield battle first, controls tempo, patient in the final third." },
  "Uruguay":                { code: "uy", flag: "🇺🇾", strength: 82, form: 72, style: "DIRECT",
    formNote: "Out earlier than expected — a below-par tournament by its standards.",
    blurb: "Physical, combative, and disciplined defensively with quick vertical outlets." },
  "Colombia":               { code: "co", flag: "🇨🇴", strength: 81, form: 82, style: "PRESS",
    formNote: "Round of 32 tie vs Ghana still to be settled; came through a tough group playing front-foot football.",
    blurb: "High-tempo pressing combined with individual flair in tight areas." },
  "Morocco":                { code: "ma", flag: "🇲🇦", strength: 80, form: 87, style: "PARK_BUS",
    formNote: "Knocked out the Netherlands on penalties after a 1-1 draw — the defense has barely been breached all tournament.",
    blurb: "Elite defensive shape and discipline — happy to absorb pressure and strike once." },
  "Japan":                  { code: "jp", flag: "🇯🇵", strength: 79, form: 80, style: "POSSESSION",
    formNote: "Out — but pushed Brazil all the way in a 2-1 defeat after a strong group stage.",
    blurb: "Disciplined pressing triggers paired with quick, tidy possession football." },
  "USA":                    { code: "us", flag: "🇺🇸", strength: 78, form: 83, style: "PRESS",
    formNote: "Controlled 2-0 win over Bosnia — the press looks sharp and the home crowd is behind them.",
    blurb: "High-energy press for 90 minutes, wants to force turnovers high up the pitch." },
  "Senegal":                { code: "sn", flag: "🇸🇳", strength: 78, form: 77, style: "COUNTER",
    formNote: "Out — went toe-to-toe with Belgium in a 3-2 extra-time classic.",
    blurb: "Athletic and direct — breaks quickly through pace on the flanks." },
  "Switzerland":            { code: "ch", flag: "🇨🇭", strength: 78, form: 82, style: "BALANCED",
    formNote: "Tidy 2-0 win over Algeria — still hasn't had to chase a game this tournament.",
    blurb: "Extremely well organized, rarely beaten twice, efficient rather than flashy." },
  "Mexico":                 { code: "mx", flag: "🇲🇽", strength: 77, form: 84, style: "POSSESSION",
    formNote: "Comfortable 2-0 over Ecuador at the Azteca — riding a huge wave of home support.",
    blurb: "Comfortable in possession, looks to control games at home in front of its crowd." },
  "Austria":                { code: "at", flag: "🇦🇹", strength: 77, form: 70, style: "PRESS",
    formNote: "Out — pressed high against Spain and was picked apart 3-0.",
    blurb: "Full-throttle gegenpressing in the mould of its coaching lineage." },
  "Ivory Coast":            { code: "ci", flag: "🇨🇮", strength: 76, form: 75, style: "DIRECT",
    formNote: "Out — led Norway 1-0 before conceding twice in a 2-1 defeat.",
    blurb: "Powerful and direct, wins physical duels and attacks crosses aggressively." },
  "Norway":                 { code: "no", flag: "🇳🇴", strength: 76, form: 80, style: "DIRECT",
    formNote: "Came from behind to beat Ivory Coast 2-1 — keeps finding goals when it needs them.",
    blurb: "Built to get the ball to its target forward quickly and attack the box in numbers." },
  "Sweden":                 { code: "se", flag: "🇸🇪", strength: 76, form: 68, style: "DIRECT",
    formNote: "Out — swept aside 3-0 by France after a mixed group stage.",
    blurb: "Physical, set-piece dangerous, prefers a direct route over intricate build-up." },
  "Algeria":                { code: "dz", flag: "🇩🇿", strength: 76, form: 71, style: "COUNTER",
    formNote: "Out — never really threatened in a 2-0 defeat to Switzerland.",
    blurb: "Quick wide players punish teams that commit numbers forward." },
  "Ghana":                  { code: "gh", flag: "🇬🇭", strength: 75, form: 74, style: "COUNTER",
    formNote: "Faces Colombia in the last round of 32 tie; reached the knockouts from a tight group.",
    blurb: "Athletic transition play with pace to burn in behind stretched defenses." },
  "Canada":                 { code: "ca", flag: "🇨🇦", strength: 74, form: 80, style: "PRESS",
    formNote: "Ground out a 1-0 win over South Africa in front of a raucous home crowd.",
    blurb: "Aggressive, youthful press backed by direct running from its wide attackers." },
  "Egypt":                  { code: "eg", flag: "🇪🇬", strength: 74, form: 76, style: "PARK_BUS",
    formNote: "Outlasted Australia on penalties after 1-1 — concedes little, creates little.",
    blurb: "Sits deep, defends in numbers, and leans on set pieces and moments of individual quality." },
  "Bosnia and Herzegovina": { code: "ba", flag: "🇧🇦", strength: 74, form: 71, style: "DIRECT",
    formNote: "Out — well beaten 2-0 by a sharper USA side.",
    blurb: "Physical and vertical, targets aerial duels and second balls." },
  "Paraguay":               { code: "py", flag: "🇵🇾", strength: 73, form: 82, style: "PARK_BUS",
    formNote: "Stunned Germany on penalties after a 1-1 draw — the tournament's biggest overachiever so far.",
    blurb: "Deep block, disciplined marking, banks on penalties and set pieces to advance." },
  "Australia":              { code: "au", flag: "🇦🇺", strength: 73, form: 73, style: "PARK_BUS",
    formNote: "Out — took Egypt to penalties but couldn't finish the job.",
    blurb: "Well-drilled low block that grinds out results rather than chasing the game." },
  "South Africa":           { code: "za", flag: "🇿🇦", strength: 72, form: 71, style: "COUNTER",
    formNote: "Out — kept it tight against Canada but lost 1-0.",
    blurb: "Compact defensively with quick breaks led by its wide forwards." },
  "Cape Verde":             { code: "cv", flag: "🇨🇻", strength: 70, form: 76, style: "PARK_BUS",
    formNote: "The tournament's surprise package — reached the round of 32 and faces Argentina.",
    blurb: "Tournament surprise package — organized, disciplined, and hard to break down." },
  "DR Congo":               { code: "cd", flag: "🇨🇩", strength: 71, form: 73, style: "DIRECT",
    formNote: "Out — gave England a real scare before falling 2-1.",
    blurb: "Physical and direct, relies on individual moments to unlock tight games." },
  "Ecuador":                { code: "ec", flag: "🇪🇨", strength: 76, form: 72, style: "BALANCED",
    formNote: "Out — shut down 2-0 by Mexico at the Azteca.",
    blurb: "Well-organized and athletic, comfortable adapting its approach to the opponent." },
};

// Round of 32 results (completed matches). aet = after extra time.
const RESULTS = [
  { round: "Round of 32", date: "Jun 28", a: "Canada", b: "South Africa", scoreA: 1, scoreB: 0, note: "" },
  { round: "Round of 32", date: "Jun 29", a: "Brazil", b: "Japan", scoreA: 2, scoreB: 1, note: "" },
  { round: "Round of 32", date: "Jun 29", a: "Paraguay", b: "Germany", scoreA: 1, scoreB: 1, note: "aet — Paraguay won 4-3 on penalties" },
  { round: "Round of 32", date: "Jun 29", a: "Morocco", b: "Netherlands", scoreA: 1, scoreB: 1, note: "aet — Morocco won 3-2 on penalties" },
  { round: "Round of 32", date: "Jun 30", a: "Norway", b: "Ivory Coast", scoreA: 2, scoreB: 1, note: "" },
  { round: "Round of 32", date: "Jun 30", a: "France", b: "Sweden", scoreA: 3, scoreB: 0, note: "" },
  { round: "Round of 32", date: "Jun 30", a: "Mexico", b: "Ecuador", scoreA: 2, scoreB: 0, note: "" },
  { round: "Round of 32", date: "Jul 1",  a: "England", b: "DR Congo", scoreA: 2, scoreB: 1, note: "" },
  { round: "Round of 32", date: "Jul 1",  a: "Belgium", b: "Senegal", scoreA: 3, scoreB: 2, note: "aet" },
  { round: "Round of 32", date: "Jul 1",  a: "USA", b: "Bosnia and Herzegovina", scoreA: 2, scoreB: 0, note: "" },
  { round: "Round of 32", date: "Jul 2",  a: "Spain", b: "Austria", scoreA: 3, scoreB: 0, note: "" },
  { round: "Round of 32", date: "Jul 2",  a: "Portugal", b: "Croatia", scoreA: 2, scoreB: 1, note: "" },
  { round: "Round of 32", date: "Jul 2",  a: "Switzerland", b: "Algeria", scoreA: 2, scoreB: 0, note: "" },
  { round: "Round of 32", date: "Jul 3",  a: "Egypt", b: "Australia", scoreA: 1, scoreB: 1, note: "aet — Egypt won 4-2 on penalties" },
  // These two Round of 32 ties were still finishing up as this snapshot was taken —
  // update with the real score once confirmed.
  { round: "Round of 32", date: "Jul 2-3", a: "Argentina", b: "Cape Verde", scoreA: null, scoreB: null, note: "Result pending — check latest scores" },
  { round: "Round of 32", date: "Jul 2-3", a: "Colombia", b: "Ghana", scoreA: null, scoreB: null, note: "Result pending — check latest scores" },
];

// Upcoming fixtures — everything still to be played, including the two
// unresolved Round of 32 ties. The Predictions tab covers all of these.
const FIXTURES = [
  { round: "Round of 32", date: "Jul 3", venue: "Atlanta",      a: "Argentina",   b: "Cape Verde", note: "tie unresolved in this snapshot" },
  { round: "Round of 32", date: "Jul 3", venue: "Vancouver",    a: "Colombia",    b: "Ghana",      note: "tie unresolved in this snapshot" },
  { round: "Round of 16", date: "Jul 4", venue: "Houston",      a: "Canada",      b: "Morocco" },
  { round: "Round of 16", date: "Jul 4", venue: "Philadelphia", a: "Paraguay",    b: "France" },
  { round: "Round of 16", date: "Jul 5", venue: "New Jersey",   a: "Brazil",      b: "Norway" },
  { round: "Round of 16", date: "Jul 5", venue: "Mexico City",  a: "Mexico",      b: "England" },
  { round: "Round of 16", date: "Jul 6", venue: "Dallas",       a: "Spain",       b: "Portugal" },
  { round: "Round of 16", date: "Jul 6", venue: "Seattle",      a: "USA",         b: "Belgium" },
  { round: "Round of 16", date: "Jul 7", venue: "Atlanta",      a: "Argentina",   b: "Egypt", note: "pending Argentina vs Cape Verde result" },
  { round: "Round of 16", date: "Jul 7", venue: "Vancouver",    a: "Switzerland", b: "Colombia", note: "pending Colombia vs Ghana result" },
];
